services:
  postgres:
    container_name: postgres-sql-real-estate
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - real_estate_network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-real-estate
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  real_estate_network:
    driver: bridge

volumes:
  postgres:
    driver: local